export const TOP_EGYPTIAN_MEDS = [
  "Panadol Extra 500mg",
  "Panadol Advance 500mg",
  "Panadol Joint 665mg",
  "Augmentin 1g",
  "Augmentin 625mg",
  "Augmentin 375mg",
  "Congestal Tablet",
  "Congestal Syrup",
  "Brufen 400mg",
  "Brufen 600mg",
  "Brufen Syrup 100mg/5ml",
  "Cataflam 50mg",
  "Cataflam 25mg",
  "Concor 5mg",
  "Concor 10mg",
  "Concor 2.5mg",
  "Concor Plus 5/12.5mg",
  "Eltroxin 50mcg",
  "Eltroxin 100mcg",
  "Glucophage 500mg",
  "Glucophage 1000mg",
  "Glucophage XR 1000mg",
  "Ketofan 50mg",
  "Ketofan 25mg",
  "Nexium 40mg",
  "Nexium 20mg",
  "Controloc 40mg",
  "Controloc 20mg",
  "Amaryl 1mg",
  "Amaryl 2mg",
  "Amaryl 3mg",
  "Diamicron MR 30mg",
  "Diamicron MR 60mg",
  "Capoten 25mg",
  "Capoten 50mg",
  "Zithromax 500mg",
  "Zithromax 250mg",
  "Hibiotic 1g",
  "Hibiotic 625mg",
  "Megamox 1g",
  "Megamox 625mg",
  "Flumox 1g",
  "Flumox 500mg",
  "Alphintern Tablet",
  "Amoclan 1g",
  "Amoclan 625mg",
  "Antinal Capsule 200mg",
  "Antinal Suspension 220mg/5ml",
  "Buscopan 10mg",
  "Buscopan Plus 10mg/500mg",
  "Colona Tablet",
  "Motilium 10mg",
  "Visceralgine 50mg",
  "Rennie Tablet",
  "Gaviscon Liquid",
  "Gaviscon Advance Liquid",
  "Spasmo-Digestin Tablet",
  "Voren 50mg",
  "Voltaren 50mg",
  "Voltaren 75mg Ampoule",
  "Voltaren Emulgel",
  "Epifen 400mg",
  "Novaldol 1000mg",
  "Paracetamol 500mg",
  "Cetafen Tablet",
  "Comtrex Tablet",
  "123 Tablet",
  "Day&Night Tablet",
  "Telfast 120mg",
  "Telfast 180mg",
  "Zyrtec 10mg",
  "Claritine 10mg",
  "Aerius 5mg",
  "Epidrone 5mg",
  "Epidrone 20mg",
  "Dexamethasone 0.5mg",
  "Betaderm Cream",
  "Betaderm Ointment",
  "Fucidin Cream",
  "Fucidin Ointment",
  "Fucidin H Cream",
  "Fucicort Cream",
  "Garamycin Cream",
  "Tobrex Eye Drops",
  "Vigamox Eye Drops",
  "Systane Ultra Eye Drops",
  "Tears Naturale Eye Drops",
  "Otrivin 0.1% Nasal Drops",
  "Otrivin 0.05% Nasal Drops",
  "Afrin Nasal Spray",
  "Ventolin Inhaler 100mcg",
  "Seretide Diskus 250mcg",
  "Seretide Diskus 500mcg",
  "Symbicort Turbuhaler 160/4.5mcg",
  "Symbicort Turbuhaler 320/9mcg",
  "Lasix 40mg",
  "Aldactone 25mg",
  "Aldactone 100mg",
  "Cordarone 200mg",
  "Lanoxin 0.25mg",
  "Plavix 75mg",
  "Aspirin Protect 100mg",
  "Jusprin 81mg",
  "Lipitor 10mg",
  "Lipitor 20mg",
  "Lipitor 40mg",
  "Crestor 10mg",
  "Crestor 20mg",
  "Zocor 20mg",
  "Livalo 2mg",
  "Ezetrol 10mg",
  "Tritace 5mg",
  "Tritace 10mg",
  "Co-Tritace 5/25mg",
  "Exforge 5/160mg",
  "Exforge 10/160mg",
  "Tareg 80mg",
  "Tareg 160mg",
  "Micardis 40mg",
  "Micardis 80mg",
  "Atacand 8mg",
  "Atacand 16mg",
  "Diovan 80mg",
  "Diovan 160mg",
  "Blopress 8mg",
  "Blopress 16mg",
  "Amlodipine 5mg",
  "Amlodipine 10mg",
  "Norvasc 5mg",
  "Norvasc 10mg",
  "Concor Cor 2.5mg",
  "Bisoprolol 5mg",
  "Inderal 10mg",
  "Inderal 40mg",
  "Tenormin 50mg",
  "Tenormin 100mg",
  "Aldomet 250mg",
  "Aldomet 500mg",
  "Daflon 500mg",
  "Hemoclar Cream",
  "Reparil Gel",
  "Lovenox 40mg Injection",
  "Lovenox 60mg Injection",
  "Clexane 40mg Injection",
  "Clexane 60mg Injection",
  "Xarelto 10mg",
  "Xarelto 15mg",
  "Xarelto 20mg",
  "Eliquis 2.5mg",
  "Eliquis 5mg",
  "Pradaxa 110mg",
  "Pradaxa 150mg",
  "Marevan 1mg",
  "Marevan 3mg",
  "Marevan 5mg",
  "Epanutin 100mg",
  "Depakine Chrono 500mg",
  "Tegretol 200mg",
  "Tegretol CR 400mg",
  "Keppra 500mg",
  "Keppra 1000mg",
  "Lamictal 25mg",
  "Lamictal 50mg",
  "Topamax 25mg",
  "Topamax 50mg",
  "Neurontin 300mg",
  "Neurontin 400mg",
  "Lyrica 75mg",
  "Lyrica 150mg",
  "Cymbalta 30mg",
  "Cymbalta 60mg",
  "Efexor XR 75mg",
  "Efexor XR 150mg",
  "Cipralex 10mg",
  "Cipralex 20mg",
  "Seroxat 20mg",
  "Seroxat CR 25mg",
  "Prozac 20mg",
  "Lustral 50mg",
  "Faverin 50mg",
  "Faverin 100mg",
  "Remeron 30mg",
  "Wellbutrin 150mg",
  "Seroquel 25mg",
  "Seroquel 200mg",
  "Zyprexa 5mg",
  "Zyprexa 10mg",
  "Risperdal 1mg",
  "Risperdal 2mg",
  "Abilify 10mg",
  "Abilify 15mg",
  "Haldol 5mg",
  "Dogmatil 50mg",
  "Deanxit Tablet",
  "Xanax 0.25mg",
  "Xanax 0.5mg",
  "Lexotanil 1.5mg",
  "Lexotanil 3mg",
  "Valium 5mg",
  "Rivotril 0.5mg",
  "Rivotril 2mg",
  "Dormicum 7.5mg",
  "Stilnox 10mg",
  "Eldepryl 5mg",
  "Sinemet 25/250mg",
  "Madopar 250mg",
  "Artane 2mg",
  "Cogentin 2mg",
  "Requip 2mg",
  "Mirapex 0.18mg",
  "Exelon 1.5mg",
  "Aricept 5mg",
  "Aricept 10mg",
  "Ebixa 10mg",
  "Nootropil 800mg",
  "Cerebrolysin 5ml Ampoule",
  "Somazina 500mg",
  "Trental 400mg",
  "Stugeron 25mg",
  "Betaserc 16mg",
  "Betaserc 24mg",
  "Microser 8mg",
  "Vastarel MR 35mg",
  "Gingko Biloba Capsule",
  "Tebokan 40mg",
  "Tebokan Forte 80mg",
  "Rhinopro Capsule",
  "Flixonase Nasal Spray",
  "Avamys Nasal Spray",
  "Nasonex Nasal Spray",
  "Rhinocort Nasal Spray",
  "Singulair 10mg",
  "Singulair 5mg Chewable",
  "Singulair 4mg Granules",
  "Kestine 10mg",
  "Levhistamine 5mg",
  "Zaditen 1mg",
  "Ketotifen 1mg",
  "Atrovent Inhaler",
  "Spiriva 18mcg Capsule",
  "Foradil Inhaler",
  "Oxis Turbuhaler",
  "Bricanyl Syrup",
  "Pulmicort Turbuhaler",
  "Miflonide 200mcg",
  "Miflonide 400mcg",
  "Clenbuterol Syrup",
  "Muco Syrup",
  "Bisolvon Tablet",
  "Mucosolvan Syrup",
  "Ambroxol Syrup",
  "Bronchicum Elixir",
  "Prospan Syrup",
  "Pentamix Syrup",
  "Guaifenesin Syrup",
  "Oplex Syrup",
  "Tusskan Syrup",
  "Codilar Syrup",
  "Sinecod Syrup",
  "Selgon Tablet",
  "Selgon Drops",
  "Silomat Syrup",
  "Kafosed Syrup",
  "Rhinotussal Capsule",
  "Piriton Tablet",
  "Phenergan 25mg",
  "Dramamine 50mg",
  "Emetrex Tablet",
  "Cortigen B6 Injection",
  "Navidoxine Tablet",
  "Zofran 4mg",
  "Zofran 8mg",
  "Kytril 1mg",
  "Emeset 4mg",
  "Motinorm 10mg",
  "Gastromotil Suspension",
  "Primperan 10mg",
  "Losec 20mg",
  "Gastrazole 20mg",
  "Omepak 20mg",
  "Pepticum 20mg",
  "Pantoloc 40mg",
  "Zurcal 40mg",
  "Pariet 20mg",
  "Dexilant 60mg",
  "Famotin 20mg",
  "Famotin 40mg",
  "Antodine 20mg",
  "Antodine 40mg",
  "Ranitidine 150mg",
  "Zantac 150mg",
  "Zantac 300mg",
  "Maalox Plus Suspension",
  "Epicogel Suspension",
  "Mucogel Suspension",
  "Phosphalugel Sachet",
  "Digestin Tablet",
  "Neo-Digestin Tablet",
  "Zymogen Tablet",
  "Festal Tablet",
  "Creon 10000",
  "Creon 25000",
  "Rowachol Capsule",
  "Ursofalk 250mg",
  "Laxomil Drops",
  "Dulcolax 5mg",
  "Agiolax Granules",
  "Minilax Enema",
  "Picolax Drops",
  "Duphalac Syrup",
  "Lactulose Syrup",
  "Senna Tablet",
  "Glycerin Suppository",
  "Imodium 2mg",
  "Lomotil Tablet",
  "Smecta Sachet",
  "Kaopectate Suspension",
  "Drotazide Tablet",
  "Flagyl 500mg",
  "Flagyl 250mg",
  "Amrizole 500mg",
  "Fasigyn 500mg",
  "Secnidazole 500mg",
  "Cipro 500mg",
  "Ciprobay 500mg",
  "Tavanic 500mg",
  "Avelox 400mg",
  "Tarivid 200mg",
  "Bactrim Forte Tablet",
  "Septrim Tablet",
  "Sutrim Tablet",
  "Macrodantin 50mg",
  "Uvamin Retard 100mg",
  "Cefzil 500mg",
  "Zinnat 500mg",
  "Zinnat 250mg",
  "Duricef 1g",
  "Duricef 500mg",
  "Curam 1g",
  "Klavox 1g",
  "E-Mox 500mg",
  "Ospamox 1000mg",
  "Amoxil 500mg",
  "Rocephin 1g Injection",
  "Cefotax 1g Injection",
  "Claforan 1g Injection",
  "Fortum 1g Injection",
  "Zinacef 750mg Injection",
  "Tienam 500mg Injection",
  "Meronem 1g Injection",
  "Invanz 1g Injection",
  "Dalacin C 300mg",
  "Clindam 300mg",
  "Vancocin 500mg",
  "Targocid 400mg",
  "Zyvox 600mg",
  "Cidomycin 80mg Injection",
  "Amikacin 500mg Injection",
  "Nebcin 80mg Injection",
  "Erythromycin 500mg",
  "Klacid 500mg",
  "Klacid XL 500mg",
  "Rulid 150mg",
  "Azomac 500mg",
  "Vibramycin 100mg",
  "Doxycost 100mg",
  "Tetracid 250mg",
  "Minocin 100mg",
  "Terramycin Eye Ointment",
  "Aureomycin Eye Ointment",
  "Bactroban Ointment",
  "Zovirax 400mg",
  "Zovirax Cream",
  "Valtrex 500mg",
  "Famvir 250mg",
  "Cymevene 500mg",
  "Tamiflu 75mg",
  "Relenza Inhaler",
  "Mycostatin Oral Drops",
  "Daktarin Oral Gel",
  "Miconaz Oral Gel",
  "Gyno-Daktarin Cream",
  "Canesten Cream",
  "Candistan Cream",
  "Diflucan 150mg",
  "Fungican 150mg",
  "Treflucan 150mg",
  "Sporanox 100mg",
  "Lamisil 250mg",
  "Lamisil Cream",
  "Terbin 250mg",
  "Grisovin 125mg",
  "Tinaderm Cream",
  "Loceryl Nail Lacquer",
  "Batrafen Cream",
  "Nizoral Shampoo",
  "Sebizole Shampoo",
  "Clopidogrel 75mg",
  "Rosuvastatin 10mg",
  "Rosuvastatin 20mg",
  "Atorvastatin 20mg",
  "Atorvastatin 40mg",
  "Simvastatin 20mg",
  "Pravastatin 20mg",
  "Losartan 50mg",
  "Valsartan 80mg",
  "Valsartan 160mg",
  "Telmisartan 40mg",
  "Telmisartan 80mg",
  "Olmesartan 20mg",
  "Irbesartan 150mg",
  "Candesartan 8mg",
  "Candesartan 16mg",
  "Enalapril 10mg",
  "Lisinopril 10mg",
  "Ramipril 5mg",
  "Captopril 25mg",
  "Perindopril 5mg",
  "Atenolol 50mg",
  "Metoprolol 50mg",
  "Carvedilol 6.25mg",
  "Carvedilol 25mg",
  "Nebivolol 5mg",
  "Diltiazem 60mg",
  "Verapamil 80mg",
  "Nifedipine 20mg",
  "Furosemide 40mg",
  "Torsemide 20mg",
  "Hydrochlorothiazide 25mg",
  "Spironolactone 25mg",
  "Eplerenone 50mg",
  "Isosorbide Dinitrate 10mg",
  "Nitroglycerin Patch",
  "Digoxin 0.25mg",
  "Warfarin 5mg",
  "Dabigatran 150mg",
  "Rivaroxaban 20mg",
  "Apixaban 5mg",
  "Heparin Injection",
  "Enoxaparin 4000 IU",
  "Insulin Mixtard 30",
  "Insulin Lantus",
  "Insulin Novorapid",
  "Metformin 850mg",
  "Gliclazide 30mg",
  "Glimepiride 2mg",
  "Glimepiride 4mg",
  "Vildagliptin 50mg",
  "Sitagliptin 100mg",
  "Saxagliptin 5mg",
  "Linagliptin 5mg",
  "Dapagliflozin 10mg",
  "Empagliflozin 10mg",
  "Empagliflozin 25mg",
  "Canagliflozin 100mg",
  "Pioglitazone 30mg",
  "Acarbose 50mg",
  "Repaglinide 1mg",
  "Levothyroxine 50mcg",
  "Levothyroxine 100mcg",
  "Carbimazole 5mg",
  "Propylthiouracil 50mg",
  "Hydrocortisone 100mg Injection",
  "Prednisone 5mg",
  "Prednisone 20mg",
  "Methylprednisolone 16mg",
  "Deflazacort 6mg",
  "Fludrocortisone 0.1mg",
  "Testosterone Injection",
  "Estradiol Patch",
  "Progesterone 400mg Suppository",
  "Clomiphene 50mg",
  "Tamoxifen 20mg",
  "Letrozole 2.5mg",
  "Anastrozole 1mg",
  "Finasteride 5mg",
  "Dutasteride 0.5mg",
  "Tamsulosin 0.4mg",
  "Alfuzosin 10mg",
  "Silodosin 8mg",
  "Sildenafil 50mg",
  "Sildenafil 100mg",
  "Tadalafil 5mg",
  "Tadalafil 20mg",
  "Vardenafil 20mg",
  "Oxybutynin 5mg",
  "Tolterodine 2mg",
  "Solifenacin 5mg",
  "Mirabegron 50mg",
  "Desmopressin 0.1mg",
  "Allopurinol 100mg",
  "Allopurinol 300mg",
  "Febuxostat 80mg",
  "Colchicine 0.5mg",
  "Probenecid 500mg",
  "Methotrexate 2.5mg",
  "Sulfasalazine 500mg",
  "Leflunomide 20mg",
  "Hydroxychloroquine 200mg",
  "Azathioprine 50mg",
  "Mycophenolate 500mg",
  "Cyclosporine 100mg",
  "Tacrolimus 1mg",
  "Infliximab 100mg Injection",
  "Adalimumab 40mg Injection",
  "Etanercept 50mg Injection",
  "Rituximab 500mg Injection",
  "Bevacizumab 400mg Injection",
  "Trastuzumab 440mg Injection",
  "Imatinib 400mg",
  "Erlotinib 150mg",
  "Bortezomib 3.5mg Injection",
  "Lenalidomide 10mg",
  "Pemetrexed 500mg Injection",
  "Docetaxel 80mg Injection",
  "Paclitaxel 300mg Injection",
  "Doxorubicin 50mg Injection",
  "Cyclophosphamide 50mg",
  "Fluorouracil 500mg Injection",
  "Cisplatin 50mg Injection",
  "Carboplatin 450mg Injection",
  "Oxaliplatin 100mg Injection",
  "Gemcitabine 1g Injection",
  "Capecitabine 500mg",
  "Irinotecan 100mg Injection",
  "Etoposide 100mg",
  "Vincristine 1mg Injection",
  "Bleomycin 15mg Injection"
];